### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by zitup** [agicommies/synthia#7]
#### Describe the bug

401 Unauthorized

####  Steps to reproduce the behavior

1. follow https://github.com/agicommies/synthia?tab=readme-ov-file#manually-on-ubuntu-2204
2. runnint a miner https://github.com/agicommies/synthia?tab=readme-ov-file#running-a-miner

#### Expected behavior

200 OK request

#### Screenshots

<img width="433" alt="image" src="https://github.com/agicommies/synthia/assets/12710516/284a048a-8fd6-4126-8551-bd1d088ca0f8">
<img width="676" alt="image" src="https://github.com/agicommies/synthia/assets/12710516/ac1794b8-7a15-4cbc-9397-e6f7ce811346">
<img width="644" alt="image" src="https://github.com/agicommies/synthia/assets/12710516/f146311e-bf9d-43d1-9bf6-9a6499a15205">
<img width="329" alt="image" src="https://github.com/agicommies/synthia/assets/12710516/d3271007-cd8d-4cc7-b156-fddcc40c8933">
<img width="747" alt="image" src="https://github.com/agicommies/synthia/assets/12710516/cb6e297f-142e-40a6-97be-7f74270e0bc8">
<img width="1248" alt="image" src="https://github.com/agicommies/synthia/assets/12710516/6b01d967-523f-4fcf-98ef-af739b8c25c4">
<img width="1249" alt="image" src="https://github.com/agicommies/synthia/assets/12710516/90e2d870-f142-4ef2-9581-83dcd5d02994">

#### Specs
- OS: Ubuntu 22.04
- Package Version: main branch
- Python3 Version: latest

**Comment by PsicoThePato** [comment]
Can you provide the output of
`poetry show communex`?
